blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Questions / Support
    url: https://github.com/iMoDzF4N4T1K/KND-Tool/discussions
    about: Please use Discussions for questions and support.
